plc_connection:
  host: "11.110.18.129"
  slot: 0

tags:
  PT1347:
    type: "float32"
    description: "DOWNSTREAM PRESSURE ESV-1001"
    unit: "kPa"
  PT1393:
    type: "float32"
    description: "UPSTREAM PRESSURE ESV-1002"
    unit: "kPa"

  PDT1343:
    type: "float32"
    description: "MAIN PUMP PU-C001E FILTER DIFFERENTIAL PRESSURE"
    unit: "kPa"
  PT1343:
    type: "float32"
    description: "MAIN PUMP PU-C001E SUCTION PRESSURE"
    unit: "kPa"
  ST0510:
    type: "float32"
    description: "PU-C001E VFD FREQUENCY"
    unit: "RPM"
  ST4001_PV:
    type: "float32"
    description: "MAIN PUMP PU-C001E ROTOR SHAFT SPEED"
    unit: "RPM"
  PT1345:
    type: "float32"
    description: "MAIN PUMP PU-C001E DISCHARGE PRESSURE"
    unit: "kPa"

  PDT1353:
    type: "float32"
    description: "MAIN PUMP PU-C001F FILTER DIFFERENTIAL PRESSURE"
    unit: "kPa"
  PT1353:
    type: "float32"
    description: "MAIN PUMP PU-C001F SUCTION PRESSURE"
    unit: "kPa"
  ST0520:
    type: "float32"
    description: "PU-C001F VFD FREQUENCY"
    unit: "RPM"
  ST4501_PV:
    type: "float32"
    description: "MAIN PUMP PU-C001F ROTOR SHAFT SPEED"
    unit: "RPM"
  PT1355:
    type: "float32"
    description: "MAIN PUMP PU-C001F DISCHARGE PRESSURE"
    unit: "kPa"

  PDT1363:
    type: "float32"
    description: "MAIN PUMP PU-C001G FILTER DIFFERENTIAL PRESSURE"
    unit: "kPa"
  PT1363:
    type: "float32"
    description: "MAIN PUMP PU-C001G SUCTION PRESSURE"
    unit: "kPa"
  ST0530:
    type: "float32"
    description: "PU-C001G VFD FREQUENCY"
    unit: "RPM"
  ST5001_PV:
    type: "float32"
    description: "MAIN PUMP PU-C001G ROTOR SHAFT SPEED"
    unit: "RPM"
  PT1365:
    type: "float32"
    description: "MAIN PUMP PU-C001G DISCHARGE PRESSURE"
    unit: "kPa"
    
  PDT1373:
    type: "float32"
    description: "MAIN PUMP PU-C001H FILTER DIFFERENTIAL PRESSURE"
    unit: "kPa"
  PT1373:
    type: "float32"
    description: "MAIN PUMP PU-C001H SUCTION PRESSURE"
    unit: "kPa"
  ST0540:
    type: "float32"
    description: "PU-C001H VFD FREQUENCY"
    unit: "RPM"
  ST5501_PV:
    type: "float32"
    description: "MAIN PUMP PU-C001H ROTOR SHAFT SPEED"
    unit: "RPM"
  PT1375:
    type: "float32"
    description: "MAIN PUMP PU-C001H DISCHARGE PRESSURE"
    unit: "kPa"
#  "Program:MainProgram.hbTimer.ACC":
#    type: "int32"
#    scale_factor: 0.001
#    description: "Program tag"

database:
  type: "sqlite"
  database: "./data"  # Папка для SQLite файла
  # batch_size и flush_interval не нужны для SQLite

polling:
  interval: "1s"
  timeout: "30s"
  