plcs:
  JAR:
    host: "192.168.0.140"
  NAR:
    host: "192.168.0.40"

tags:
  PT0386:
    plc: NAR
    type: "float32"
    description: "SUCTION PRESSURE"
    unit: "kPa"
  PT0356:
    plc: JAR
    type: "float32"
    description: "SUCTION PRESSURE JAR"
    unit: "kPa"

#  "Program:MainProgram.hbTimer.ACC":
#    type: "int32"
#    scale_factor: 0.001
#    description: "Program tag"

database:
  type: "sqlite"
  database: "./data"  # Папка для SQLite файла
  # batch_size и flush_interval не нужны для SQLite

polling:
  interval: "0.25s"
  timeout: "30s"
  